export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const MESSAGE_SENT = "MESSAGE_SENT"
export const COMMUNITY_CHAT = "COMMUNITY_CHAT";
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const TYPING = "TYPING";